server.port=8083
spring.application.name=bff-cajero

# Importar configuracion desde Config Server (si esta disponible)
spring.config.import=optional:configserver:http://localhost:8888

# Configuracion HTTPS / SSL con Certificado Digital
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=bancoxyz2026
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz

# URL del Core Bancario (HTTPS)
bank.core.url=https://localhost:8080/api/core
bank.core.internal-api-key=SecretCoreKeyBancoXYZ2026

# JWT Config
bank.jwt.secret=BancoXYZSuperSecretKeyClaveSeguraParaTokensJWT2026MovilWebATM
bank.jwt.expiration-ms=86400000

# Registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
